apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    name: ingester-rollout-pdb
  name: ingester-rollout-pdb
  namespace: tracing
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      rollout-group: ingester
