apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-operator-rolebinding
  namespace: tracing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rollout-operator-role
subjects:
- kind: ServiceAccount
  name: rollout-operator
  namespace: tracing
