apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    rollout-max-unavailable: "1"
  labels:
    rollout-group: ingester
  name: ingester-zone-c
  namespace: tracing
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      name: ingester-zone-c
      rollout-group: ingester
  serviceName: ingester
  template:
    metadata:
      annotations:
        config_hash: 9c334fb94b01be9a51cd2aa424acbd9c
      labels:
        name: ingester-zone-c
        rollout-group: ingester
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: rollout-group
                operator: In
                values:
                - ingester
              - key: name
                operator: NotIn
                values:
                - ingester-zone-c
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -config.expand-env=true
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=1024
        - -target=ingester
        env:
        - name: AVAILABILITY_ZONE
          value: c
        image: grafana/tempo:latest
        imagePullPolicy: IfNotPresent
        name: ingester
        ports:
        - containerPort: 3200
          name: prom-metrics
        readinessProbe:
          httpGet:
            path: /ready
            port: 3200
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "5"
            memory: 5Gi
          requests:
            cpu: "3"
            memory: 3Gi
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
        - mountPath: /var/tempo
          name: ingester-data
        - mountPath: /overrides
          name: overrides
      terminationGracePeriodSeconds: 1200
      volumes:
      - configMap:
          name: tempo-ingester
        name: tempo-conf
      - configMap:
          name: tempo-overrides
        name: overrides
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: ingester
      name: ingester-data
      namespace: tracing
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: fast
